---
- name: Pull MySQL from Docker Hub and push to Nexus via Podman
  hosts: kube-node
  become: true
  vars:
    source_image: docker.io/library/mysql:latest
    nexus_host: 10.110.188.231
    nexus_repo: docker-hosted
    target_image: "{{ nexus_host }}/{{ nexus_repo }}/mysql:latest"
    nexus_user: firas
    nexus_password: firas1234

  tasks:

    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Login to Nexus
      shell: podman login {{ nexus_host }} -u {{ nexus_user }} -p {{ nexus_password }}
      register: login_output
      changed_when: "'Login Succeeded' in login_output.stdout"

    - name: Pull MySQL image
      shell: podman pull {{ source_image }}

    - name: Tag image for Nexus
      shell: podman tag {{ source_image }} {{ target_image }}

    - name: Push image to Nexus
      shell: podman push {{ target_image }}
