---
- name: Pull MySQL from Docker Hub and push to Nexus using skopeo
  hosts: localhost
  become: true
  vars:
    source_image: docker://docker.io/library/mysql:latest
    nexus_host: 10.110.188.231:8082
    nexus_repo: docker-hosted
    target_image: "docker://{{ nexus_host }}/firas_barkia/mysql:lts"
    nexus_user: firas
    nexus_password: firas1234

  tasks:

    - name: Install skopeo
      apt:
        name: skopeo
        state: present
        update_cache: true

    - name: Copy image from Docker Hub to Nexus registry using skopeo
      shell: >
        skopeo copy {{ source_image }} {{ target_image }}
        --dest-creds={{ nexus_user }}:{{ nexus_password }}

